### ISSUE TITLE
still getting ```markdown in some responses

### ISSUE THREAD

**Issue by tylermaran** [getomni-ai/zerox#11]
This is a problem with the `formatMarkdown` regex. Just need to do a bit more string parsing to make sure the `'''markdown` deliminators are stripped out. 

https://github.com/getomni-ai/zerox/blob/main/node-zerox/src/utils.ts#L13

**Comment by xdotli** [comment]
https://github.com/getomni-ai/zerox/pull/17
resolved in this PR
