### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by RazvanMihaiPopa** [getomni-ai/zerox#14]
Could i use the API but add a new prompt? Or is that not possible.

**Comment by tylermaran** [comment]
Hey @RazvanMihaiPopa, happy to allow for custom prompting. 
We can make that an optional field to override the default prompt. I'll take a look at that sometime this week.

**Comment by pradhyumna85** [comment]
@RazvanMihaiPopa I have raised a PR https://github.com/getomni-ai/zerox/pull/21 which is not merged yet but you can go ahead and test it, you can pass custom system prompt to override zerox's default system prompt.
Install python package: `pip install git+https://github.com/pradhyumna85/zerox.git@multi-provider-support-pysdk`
Follow this readme example: [here](https://github.com/pradhyumna85/zerox/blob/multi-provider-support-pysdk/README.md#usage-python-sdk---supports-vision-models-from-different-providers-like-openai-azure-openai-anthropic-aws-bedrock-etc)
