### ISSUE TITLE
Unable to copy files

### ISSUE THREAD

**Issue by edishu** [getomni-ai/zerox#5]
When trying this I get the error `operation not permitted`

```
[Error: EPERM: operation not permitted, copyfile '/home/uber.pdf' -> 'tmp/your-app-temp/uber.pdf'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'copyfile',
  path: '/home/uber.pdf',
  dest: 'tmp/your-app-temp/uber.pdf'
}
```

**Comment by tylermaran** [comment]
hey @edishu, can you share the code snippit you're using to call zerox? I'd like to see if I can replicate. 

We run an `ensureDir` check on the temp folder the app uses, but there might be some permission errors.
