### ISSUE TITLE
Existing workflows to handle images in PDF.

### ISSUE THREAD

**Issue by rajaravivarma-r** [getomni-ai/zerox#51]
Hi, thanks for the great tool. I had good success with it, especially when the PDF has code snippets in them.

I would like to know if there are existing features/workflows to handle images in certain pages. I was wondering if it could be extracted into an SVG or base64 encoded image and embedded in the markdown itself, hoping it would be rendered by certain markdown viewers.

**Comment by tylermaran** [comment]
Hey @rajaravivarma-r, this is something we've been interested in as well. 

I'm thinking we could extract the images as a local file path and return them in an array after the response. Something like: 

```js
{
  completionTime: 10038,
  fileName: 'invoice_36258',
  inputTokens: 25543,
  outputTokens: 210,
  pages: [
    {
      content: '# INVOICE # 36258\n' +
        '**Date:** Mar 06 2012  \n' +
        '**Ship Mode:** First Class  \n' +
        '**Balance Due:** $50.10  \n' +
        '## Product Image:\n' +
        '[image](1234):'
      page: 1,
      contentLength: 747
    }
  ],
  images: [
    {
      id: 1234,
      localUrl: 'path/to/image.png'
    }
  ]
}
```

Need to think through how we would correctly tag the image inside the markdown response (especially if there are a lot of them).

**Comment by rajaravivarma-r** [comment]
@tylermaran Thank you. I would be interested in converting the pages into HTML, so that it can be converted to epub. Is that possible?

**Comment by tylermaran** [comment]
Hey @rajaravivarma-r. I don't think html export would be something we officially support in the library. But it should be a pretty quick conversion from the zerox results.

Since the content is markdown, you can use a markdown => html library to render the results. 

```py
import markdown

# zerox_response = zerox(...)

for page in zerox_response['pages']:
    content = page['content']
    html = markdown.markdown(content)

    file_name = f"{data['fileName']}.html"
    with open(file_name, 'w') as f:
        f.write(html)

    print(f"HTML content saved to {file_name}")
```

also are you thinking of using zerox to scan pages (with extracted images) into an epub file? I love the use case!

**Comment by rajaravivarma-r** [comment]
Huh! How did I not think of that. Thank you @tylermaran
