### ISSUE TITLE
Azure OpenAI

### ISSUE THREAD

**Issue by AlexVialaBellander** [getomni-ai/zerox#95]
In Azure, deployments are often named other things than the model names, for instance "gpt-4o" could be named "wrapper-api-gpt-4o". This causes the mapping to not recognise the model since it is not in the mapping json.

I would suggest an additional parameter that differentiates the deployment name used for querying the api vs the model selector.

**Comment by tylermaran** [comment]
Hey @AlexVialaBellander. Were you able to resolve this? Let me know if theres anything I can add to the documentation.
